name: Flask CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Check database
      run: python check_db.py

    - name: Run unit tests
      run: |
        python -m pytest tests/ -v --cov=app --cov-report=xml

    - name: Start Flask
      run: |
        python app.py &
        sleep 5
        curl -f http://localhost:5000 || echo "App started but no route at /"
        