name: Flask CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install requirements
      run: |
        pip install -r app/requirements.txt
        pip install pytest pytest-cov
        pip install pylint

    - name: Check database
      run: python check_db.py

    - name: Run Pylint
      run: |
        pylint app/ tests/ *.py --exit-zero

    - name: Run unit tests
      run: |
        python -m pytest tests/ -v --cov=app --cov-report=xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Start Flask
      run: |
        python app.py &
        sleep 5
        curl -f http://localhost:5000 || echo "App started but no route at /"