name: Basic Flask CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install requirements
      run: pip install -r app/requirements.txt

    - name: Check database
      run: python check_db.py

    - name: Start Flask
      run: |
        python app.py &
        sleep 5
        curl -f http://localhost:5000 || echo "App started but no route at /"