name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # 2. Install dependencies
    - name: Install dependencies
      run: |
        echo "Installing project dependencies..."
        pip install -r requirements.txt
    
    # 3. Check database setup
    - name: Verify database
      run: |
        echo "Running database check..."
        python check_db.py
        if [ $? -ne 0 ]; then
          echo "Database check failed!"
          exit 1
        fi
    
    # 4. Run application with proper Flask environment
    - name: Run application
      env:
        FLASK_APP: app.py
        FLASK_ENV: development
      run: |
        echo "Starting Flask application..."
        flask run --host=0.0.0.0 --port=5000 &
        sleep 10  # Increased wait time for Flask startup
        
        echo "Checking application health..."
        curl -s http://localhost:5000/health || curl -s http://localhost:5000
        if [ $? -ne 0 ]; then
          echo "Application failed to start!"
          exit 1
        fi
        echo "Application is running successfully!"